### PR TITLE
fix: Ensure that tesselating an unprojectable edge does not result in a crash

### LINKED ISSUE #43: Crash in exporting of polygon with orthographic projection and tessellation
Haven't converted it to a s2geography C++ test, but reproducer using spherely:

```python
import pyarrow as pa
import geoarrow.pyarrow as ga
import spherely

wkb = bytes.fromhex("0103000000010000000d0000003b70ce88d2ee4dc01ea7e8482e2354c0ea95b20c71144ec0158c4aea044054c0ffb27bf2b0204fc0107a36ab3e3754c05e4bc8073d1f50c0ac8bdb68003b54c05ddc4603786f50c0a1f831e6ae2554c05ddc4603786f50c01ea7e8482e2354c0c3f5285c8f9250c04694f6065f1054c0cac342ad690250c0c9e53fa4df1254c0e2e995b20cf14ec04ca60a46251954c06f1283c0ca914ec0d712f241cffe53c012a5bdc1174e4ec0b1bfec9e3ce853c05305a3923ac94dc0265305a3920254c03b70ce88d2ee4dc01ea7e8482e2354c0")

geog = spherely.from_geoarrow(pa.array([wkb]),geometry_encoding="WKB")[0]
print(geog)
# POLYGON ((-59.5721 -80.0402, -60.6101 -79.6287, -61.139 -79.9814, -61.8832 -80.3929, -64.0377 -80.2949, -66.29 -80.2558, -65.7417 -80.5497, -65.7417 -80.5888, -64.4881 -80.9219, -62.2554 -80.8632, -60.1597 -81.0003, -59.8658 -80.5497, -59.5721 -80.0402))

result1 = pa.array(spherely.to_geoarrow(
    [geog], output_schema=ga.wkt(), projection=spherely.Projection.orthographic(-35.8273, 44.78515)
))
print(result1[0].as_py())
# POLYGON ((-0.069644 -0.810583, -0.075463 -0.813297, -0.074379 -0.809717, -0.073306 -0.805417, -0.079688 -0.804244, -0.085806 -0.802284, -0.081883 -0.800376, -0.081548 -0.800044, -0.075675 -0.798393, -0.070674 -0.800919, -0.064454 -0.801424, -0.066884 -0.805755, -0.069644 -0.810583))

# same projection, now asking for planar edges -> using tessellation
result2 = pa.array(spherely.to_geoarrow(
    [geog], output_schema=ga.wkt(), projection=spherely.Projection.orthographic(-35.8273, 44.78515), planar=True
))
```

This last one crashes. Gdb backtrace:

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fff42e9b1d8 in S2::GetPointOnLine(S2Point const&, S2Point const&, S1Angle) () from /home/joris/conda/envs/spherely-dev2/lib/libs2.so.0
(gdb) bt
#0  0x00007fff42e9b1d8 in S2::GetPointOnLine(S2Point const&, S2Point const&, S1Angle) () from /home/joris/conda/envs/spherely-dev2/lib/libs2.so.0
#1  0x00007fff42e9bcca in S2::Interpolate(S2Point const&, S2Point const&, double) () from /home/joris/conda/envs/spherely-dev2/lib/libs2.so.0
#2  0x00007fff42e9e2b8 in S2EdgeTessellator::EstimateMaxError(Vector2<double> const&, S2Point const&, Vector2<double> const&, S2Point const&) const () from /home/joris/conda/envs/spherely-dev2/lib/libs2.so.0
#3  0x00007fff42e9e61f in S2EdgeTessellator::AppendProjected(Vector2<double> const&, S2Point const&, Vector2<double> const&, S2Point const&, std::vector<Vector2<double>, std::allocator<Vector2<double> > >*) const () from /home/joris/conda/envs/spherely-dev2/lib/libs2.so.0
#4  0x00007fff42e9e74a in S2EdgeTessellator::AppendProjected(Vector2<double> const&, S2Point const&, Vector2<double> const&, S2Point const&, std::vector<Vector2<double>, std::allocator<Vector2<double> > >*) const () from /home/joris/conda/envs/spherely-dev2/lib/libs2.so.0
#5  0x00007fff42e9e74a in S2EdgeTessellator::AppendProjected(Vector2<double> const&, S2Point const&, Vector2<double> const&, S2Point const&, std::vector<Vector2<double>, std::allocator<Vector2<double> > >*) const () from /home/joris/conda/envs/spherely-dev2/lib/libs2.so.0
#6  0x00007fff42e9e74a in S2EdgeTessellator::AppendProjected(Vector2<double> const&, S2Point const&, Vector2<double> const&, S2Point const&, std::vector<Vector2<double>, std::allocator<Vector2<double> > >*) const () from /home/joris/conda/envs/spherely-dev2/lib/libs2.so.0
#7  0x00007fff42e9e74a in S2EdgeTessellator::AppendProjected(Vector2<double> const&, S2Point const&, Vector2<double> const&, S2Point const&, std::vector<Vector2<double>, std::allocator<Vector2<double> > >*) const () from /home/joris/conda/envs/spherely-dev2/lib/libs2.so.0
#8  0x00007fff42e9e74a in S2EdgeTessellator::AppendProjected(Vector2<double> const&, S2Point const&, Vector2<double> const&, S2Point const&, std::vector<Vector2<double>, std::allocator<Vector2<double> > >*) cons
....
```

### PR DESCRIPTION
**Pull request by paleolimbot**
Closes #43.

This PR updates the orthographic projection to return nan, nan when attempting to project a point that would otherwise not be visible on that hemisphere of the earth. Allowing such a point to be projected led to an unstable situtation when points were repeatedly roundtripped (e.g., in edge tessellation).

This also applies formatting and fixes a compiler warning (I haven't yet set up a pre-commit!).

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Thanks a lot!

> This PR updates the orthographic projection to return nan, nan when attempting to project a point that would otherwise not be visible on that hemisphere of the earth.

Ah, so it was because I was reprojecting the geometries of the whole world, instead of first taking an intersection with the visible hemisphere based on the center point ..

File: src/s2geography/projections.cc [hunk 1]
```diff
@@ -32,11 +36,19 @@ class OrthographicProjection: public S2::Projection {
...
+      return R2Point(out.y(), out.z());
+    } else {
+      return R2Point(NAN, NAN);
+    }
   }
 
   // Converts a projected 2D point to a point on the sphere.
   S2Point Unproject(const R2Point& p) const {
+    if (std::isnan(p.x()) || std::isnan(p.y())) {
+      throw Exception("Can't unproject orthographic for non-finite point");
```
Comment (jorisvandenbossche) [inline src/s2geography/projections.cc:49]: This error message is a bit confusing if you get this from a s2geography -> projected geoarrow conversion, because you are projecting in that case, not unprojecting. The fact that under the hood it unprojects for `EstimateMaxError` is not something the user can know.

Now, not sure if there is an easy way to avoid that (because it could also be called just for Unproject with invalid nan values), and for spherely we can catch the error and provide a better one

Comment (paleolimbot) [reply src/s2geography/projections.cc:49]: Feel free to improve...this directly solves the issue of a crash (which otherwise is very difficult to detect!). I wish S2 let you set the recursion limit here (which is a better indication of an unstable project/unproject pairing).

In spherely if you're doing an orthographic projection you also will want to run it by an intersection of the hemisphere (which will eliminate points that would return this value):

https://github.com/r-spatial/s2/blob/main/R/plot.R#L77-L96

Comment (jorisvandenbossche) [reply src/s2geography/projections.cc:49]: > In spherely if you're doing an orthographic projection you also will want to run it by an intersection of the hemisphere (which will eliminate points that would return this value):
> 
> https://github.com/r-spatial/s2/blob/main/R/plot.R#L77-L96

Yep, was just working on that :)
